version: '3'
services:
  db:
    build: ./db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ./db/data:/var/lib/mysql
    tty: true
  web:
    build: ./web
    command: systemctl enable httpd
    ports:
      - '80:80'
    volumes:
      - ../:/var/www/html
      - ../vendor:/usr/local/vendor
    tty: true
    privileged: true
    command: /sbin/init
    depends_on:
      - db
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
